import Head from "next/head";
import { useSession } from "next-auth/react";
import { useRouter } from "next/router";
import AllImages from "../components/AllImages/AllImages";
import NavSearch from "../components/NavSearch/NavSearch";

import s from "@/styles/Home.module.css";

export default function Home() {
  const router = useRouter();
  const { data: session } = useSession();
  // TODO modify this test with real data

  const allImages: number[] = [
    10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24,
  ];

  // if user role is NONE, route to onboarding form
  if (session?.user?.role == "NONE") {
    router.push("/auth/new-user");
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={s.main}>
        <h1>Home</h1>
        {session?.user ? (
          <p>You are signed in as a {session.user.role}</p>
        ) : null}
        <h2>Find your open source images</h2>
      </main>

      <NavSearch />
      <AllImages />
    </>
  );
}
