import Head from "next/head";
import { useState } from "react";
import { useSession } from "next-auth/react";
import { useRouter } from "next/router";
import prisma from "@/lib/prisma";
import type { Image } from "@/lib/prisma";
import SearchBar from "@/components/Search/SearchBar";
import s from "@/styles/Home.module.css";

type Props = {
  allImages: Image[];
};

export default function Home({ allImages }: Props) {
  const router = useRouter();
  const { data: session } = useSession();

  const [searchResults, setSearchResults] = useState(allImages);
  const searchBarProps = {
    allImages,
    searchResults,
    setSearchResults,
  };

  // if user role is NONE, route to onboarding form
  if (session?.user?.role == "NONE") {
    router.push("/auth/new-user");
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={s.main}>
        <SearchBar {...searchBarProps} />
        <h1>Home</h1>
        {session?.user ? (
          <p>You are signed in as a {session.user.role}</p>
        ) : null}
      </main>
    </>
  );
}

export async function getServerSideProps() {
  const allImages = await prisma.image.findMany();
  console.log(allImages);
  return {
    props: {
      session: {
        images: allImages,
      },
    },
  };
}
